steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/newsletter-frontend:v1', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/newsletter-frontend:v1']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'newsletter-frontend'
      - '--image=gcr.io/$PROJECT_ID/newsletter-frontend:v1'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--timeout=300s'
      - '--set-env-vars=NEXT_PUBLIC_API_URL=https://newsletter-aggregator-857170198287.us-central1.run.app'

  # Create a tagged production version
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/newsletter-frontend:v1', 'gcr.io/$PROJECT_ID/newsletter-frontend:latest']

  # Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/newsletter-frontend:latest']

images:
  - 'gcr.io/$PROJECT_ID/newsletter-frontend:v1'
  - 'gcr.io/$PROJECT_ID/newsletter-frontend:latest' 