steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/newsletter-aggregator:$BUILD_ID', '.']
    id: 'Build Image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/newsletter-aggregator:$BUILD_ID']
    id: 'Push Image'

  # Substitute the image placeholder in service.yaml with the actual image name and tag
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s|gcr.io/PROJECT_ID/newsletter-aggregator:TAG|gcr.io/$PROJECT_ID/newsletter-aggregator:$BUILD_ID|g" service.yaml
    id: 'Prepare Service Config'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'services'
      - 'replace'
      - 'service.yaml'
      - '--region=${_REGION}'
      - '--platform=managed'
    id: 'Deploy to Cloud Run'

# Variables
substitutions:
  _REGION: 'us-central1'  # Default region

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/newsletter-aggregator:$BUILD_ID'

# Set build timeout to 15 minutes
timeout: '900s' 