steps:
  # Build the container image using the commit SHA as the tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/newsletter-aggregator:$BUILD_ID', '.']
    id: 'Build Backend Image'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/newsletter-aggregator:$BUILD_ID']
    id: 'Push Backend Image'

  # Create a Cloud Deploy release for the backend service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud # Explicitly set the entrypoint
    args:
      - 'deploy'
      - 'releases'
      - 'create'
      # Release name: Use a timestamp or short SHA for uniqueness
      - 'rel-${SHORT_SHA}-${BUILD_ID}'
      - '--delivery-pipeline=newsletter-aggregator-backend-pipeline' # Matches the pipeline name in clouddeploy.yaml
      - '--region=us-central1'
      # Point to the image built and pushed in earlier steps
      - '--images=newsletter-aggregator=gcr.io/$PROJECT_ID/newsletter-aggregator:$BUILD_ID'
      # Optional: Add annotations if needed
      # - '--annotations=commit_id=$COMMIT_SHA'
      - '--description=Backend release triggered by commit $SHORT_SHA'
      # Ensure skaffold.yaml exists in the root directory or specify path with --skaffold-file
    id: 'Create Cloud Deploy Release'

# List the specific image artifact produced by this build.
images:
  - 'gcr.io/$PROJECT_ID/newsletter-aggregator:$BUILD_ID'

# Optional: Set build timeout
# timeout: '600s' 