swagger: '2.0'
info:
  title: Newsletter Aggregator API
  description: API for the Newsletter Aggregator service
  version: 1.0.0
host: newsletter-aggregator-api-7mdxrxbo2q-uc.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://newsletter-aggregator-api-7mdxrxbo2q-uc.a.run.app
  protocol: h2
paths:
  /api/update/status:
    get:
      operationId: getUpdateStatus
      security:
        - api_key: []
      x-google-backend:
        address: https://newsletter-aggregator-api-7mdxrxbo2q-uc.a.run.app
        deadline: 10.0
      responses:
        '200':
          description: Update status response
          schema:
            type: object
            properties:
              status:
                type: string
              last_update:
                type: string
    options:
      summary: CORS support for update status
      operationId: corsUpdateStatus
      x-google-backend:
        address: https://newsletter-aggregator-api-7mdxrxbo2q-uc.a.run.app
        deadline: 10.0
      responses:
        '204':
          description: CORS headers returned successfully

  /api/update/start:
    post:
      operationId: startUpdate
      security:
        - api_key: []
      x-google-backend:
        address: https://newsletter-aggregator-api-7mdxrxbo2q-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
        deadline: 30.0
      responses:
        '200':
          description: Update started successfully
          schema:
            type: object
            properties:
              message:
                type: string
    options:
      summary: CORS support
      operationId: corsStartUpdate
      x-google-backend:
        address: https://newsletter-aggregator-api-7mdxrxbo2q-uc.a.run.app
        path_translation: APPEND_PATH_TO_ADDRESS
        deadline: 30.0
      responses:
        '204':
          description: CORS headers returned successfully

  /api/articles:
    get:
      operationId: getArticles
      security:
        - api_key: []
      x-google-backend:
        address: https://newsletter-aggregator-api-7mdxrxbo2q-uc.a.run.app
        deadline: 10.0
      parameters:
        - name: topic
          in: query
          type: string
          required: false
        - name: limit
          in: query
          type: integer
          required: false
      responses:
        '200':
          description: List of articles
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
                url:
                  type: string
                date:
                  type: string
                source:
                  type: string
                topic:
                  type: string

  /api/topics:
    get:
      operationId: getTopics
      security:
        - api_key: []
      x-google-backend:
        address: https://newsletter-aggregator-api-7mdxrxbo2q-uc.a.run.app
        deadline: 10.0
      responses:
        '200':
          description: List of topics
          schema:
            type: array
            items:
              type: string

  /api/rag:
    post:
      operationId: queryRag
      security:
        - api_key: []
      x-google-backend:
        address: https://newsletter-aggregator-api-7mdxrxbo2q-uc.a.run.app
        deadline: 30.0
      parameters:
        - name: query
          in: body
          required: true
          schema:
            type: object
            properties:
              query:
                type: string
      responses:
        '200':
          description: RAG query response
          schema:
            type: object
            properties:
              answer:
                type: string
              sources:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    url:
                      type: string

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header

x-google-endpoints:
  - name: newsletter-aggregator-gateway-axs105xr.uc.gateway.dev
    allowCors: true

x-google-allow-cors:
  allow-origins:
    - https://newsletter-aggregator-knap.vercel.app
    - https://newsletter-aggregator.vercel.app
    - http://localhost:3000
  allow-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allow-headers:
    - Content-Type
    - Authorization
  allow-credentials: true
  max-age: 3600 