swagger: '2.0'
info:
  title: Newsletter Aggregator API
  description: API Gateway for Newsletter Aggregator service
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-endpoints:
  - name: ${GATEWAY_URL}
    allowCors: true
paths:
  /api/**:
    get:
      summary: Proxy GET requests to the backend
      operationId: proxyApiGet
      x-google-backend:
        address: https://newsletter-aggregator-SERVICE_PROJECT_NUMBER.a.run.app/api/${request.path.wildcard.path_to_replace}
      responses:
        '200':
          description: OK
    post:
      summary: Proxy POST requests to the backend
      operationId: proxyApiPost
      x-google-backend:
        address: https://newsletter-aggregator-SERVICE_PROJECT_NUMBER.a.run.app/api/${request.path.wildcard.path_to_replace}
      responses:
        '200':
          description: OK
    put:
      summary: Proxy PUT requests to the backend
      operationId: proxyApiPut
      x-google-backend:
        address: https://newsletter-aggregator-SERVICE_PROJECT_NUMBER.a.run.app/api/${request.path.wildcard.path_to_replace}
      responses:
        '200':
          description: OK
    delete:
      summary: Proxy DELETE requests to the backend
      operationId: proxyApiDelete
      x-google-backend:
        address: https://newsletter-aggregator-SERVICE_PROJECT_NUMBER.a.run.app/api/${request.path.wildcard.path_to_replace}
      responses:
        '200':
          description: OK
  /:
    get:
      summary: Proxy root GET requests to the backend
      operationId: proxyRootGet
      x-google-backend:
        address: https://newsletter-aggregator-SERVICE_PROJECT_NUMBER.a.run.app/
      responses:
        '200':
          description: OK
  /**:
    get:
      summary: Proxy all other GET requests to the backend
      operationId: proxyOtherGet
      x-google-backend:
        address: https://newsletter-aggregator-SERVICE_PROJECT_NUMBER.a.run.app/${request.path.wildcard.path_to_replace}
      responses:
        '200':
          description: OK
  /api/{proxy+}:
    options:
      summary: CORS support
      description: Enable CORS by returning correct headers
      operationId: corsSupport
      x-google-backend:
        address: ${BACKEND_URL}
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '204':
          description: CORS headers returned
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: string
              description: Origins allowed to make requests
            Access-Control-Allow-Methods:
              schema:
                type: string
              description: Methods allowed for CORS requests
            Access-Control-Allow-Headers:
              schema:
                type: string
              description: Headers allowed in CORS requests
    x-google-backend:
      address: ${BACKEND_URL}
      path_translation: APPEND_PATH_TO_ADDRESS 