apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: newsletter-aggregator
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        autoscaling.knative.dev/minScale: '1'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: gcr.io/PROJECT_ID/newsletter-aggregator:TAG
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: '1'
              memory: 512Mi
          # Environment variables will be populated from env.yaml
          # The actual env vars will be managed by the Cloud Build configuration 